1.0.5

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -152,7 +152,12 @@ jobs:
               git reset --hard
 
       - name: Copy index.html from dist/browser/test to dist root
-        run: cp dist/ride-sharing-app/browser/index.html ./index.html
+        run:  |
+           
+              if ! cp dist/ride-sharing-app/browser/index.html ./index.html/ 2>/dev/null; then
+                echo "Error: File not found or copy failed"
+                exit 1
+              fi
 
       # Copy index.html to the root of the dist directory
       # Copies the `index.html` file from the Angular build output to the root of the `dist` folder.
