Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -3,7 +3,6 @@ name: build-test-deploy
 on: 
   push:
     branches:
-      - main
       - gh-pages
   workflow_dispatch:  
 
@@ -19,10 +18,10 @@ jobs:
           node-version: '20.x'
       - run: npm install
       - run: npm run build -- --output-path=dist --base-href=/ride-sharing-app/
+      - name: list dist directory for debug
+        run: ls -R dist
       - name: verify index.html
-        run: if [ ! -f dist/browser/index.html ]; then echo "index.html not found in browser directory!"; exit 1; fi
-      - name: copy index.html to dist root
-        run: cp dist/browser/index.html dist/index.html
+        run: if [ ! -f dist/index.html ]; then echo "index.html not found in dist directory!"; exit 1; fi
 
   deploy:
     needs: build
